<a href="https://colab.research.google.com/github/ibtihalalf/Exercises1/blob/main/Week2/M2-Exercises_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [ ]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

### Step 3. Assign it to a variable called chipo.

In [ ]:
chipo = pd.read_csv(url , sep ='\t')

### Step 4. How many products cost more than $10.00?

In [ ]:
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [31]:
chipo['item_price'] = chipo['item_price'].apply(lambda x: float(x[1:]) if isinstance(x, str) else x)

chipo['product_price'] = chipo['item_price'] / chipo['quantity']

chipo_unique = chipo.drop_duplicates(['item_name','choice_description'])

filtered_chipo = chipo_unique[chipo_unique['product_price'] > 10]

print('the number of products that cost more than $10.00 is', filtered_chipo.shape[0])

the number of products that cost more than $10.00 is 707

### Step 5. What is the price of each item?
###### print a data frame with only three columns item_name choice_description and product_price

In [32]:
filtered_chipo[["item_name","choice_description","product_price"]].reset_index(drop=True)

,item_name,choice_description,product_price
0,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
3,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
4,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
...,...,...,...
702,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.75
703,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",11.75
704,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
705,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
706,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25

### Step 6. Sort by the name of the item

In [33]:
chipo.sort_values(by='item_name')

,order_id,quantity,item_name,choice_description,item_price,unit_price,product_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49,6.49
...,...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [35]:
chipo.loc[chipo["item_price"].idxmax()]["quantity"]

np.int64(15)

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [36]:
chipo[chipo['item_name'] == 'Veggie Salad Bowl']['quantity'].sum()

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [37]:
chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)].shape[0]

20